# Generated by Django 4.2.4 on 2023-08-02 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Board',
        ),
    ]
